services:
  envoy:
    image: envoyproxy/envoy:v1.33-latest
    command:
      - envoy
      - --log-level debug
      - --config-path /envoy.yaml
    volumes:
      - ./envoy.yaml:/envoy.yaml
    restart: on-failure
    ports:
      - 80:80

  opa:
    image: openpolicyagent/opa:1.3.0-envoy-5
    command: 
      - run
      - --server
      - --addr=0.0.0.0:8181
      - --diagnostic-addr=0.0.0.0:8282
      - --config-file=/config.yaml
      - --log-level=info
      - /app/policies
    restart: on-failure
    ports:
      - "38181:8181"
      - "38282:8282"
    volumes:
      - ./opa/policies:/app/policies
      - ./opa/config.yaml:/config.yaml

  backend:
    image: hashicorp/http-echo
    command: ['-listen=:8000', '-text=access granted']
    restart: on-failure
    ports:
      - "8000:8000"
