services:
  nginx:
    image: nginx:1.25.1
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  pdp:
    build:
      context: ./pdp
    restart: on-failure

  backend:
    image: hashicorp/http-echo
    command: ['-listen=:8000', '-text=access granted']
    restart: on-failure
    ports:
      - "8000:8000"
